force-app/main/default/objects/Medical_card__c/Medical_card__c.object-meta.xml
<CustomObject>
    <label>Medical card</label>
    <nameField>
        <label>Medical card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_card__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Medical cards</relationshipLabel>
    <relationshipName>Medical_cards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/VisitService.cls
public with sharing class VisitService {  

    @AuraEnabled( cacheable = true )  
    public static List<VisitWrapper> getTodayVisit() {                 
    List<VisitWrapper> listVisitWrapper = new List<VisitWrapper>();

    for (Visit__c visit : [ SELECT Id, Patient__r.Name, Doctor__c, StartDate__c 
                        FROM Visit__c
                        WHERE StartDate__c = TODAY
                        ]) {

    DateTime now = System.now();
    DateTime nowMinus15Min = now.addMinutes(-15);
    DateTime nowPlus15Min = now.addMinutes(15);

    VisitWrapper VisitWrap = new VisitWrapper();
    VisitWrap.Id = visit.Id;
    VisitWrap.PatientName = visit.Patient__r.Name;
    VisitWrap.StartDate = visit.StartDate__c.format( 'dd/MM HH:mm' );
    VisitWrap.isActive = !(visit.StartDate__c.addHours(4) >= nowMinus15Min && visit.StartDate__c.addHours(4) <= nowPlus15Min);
    listVisitWrapper.add(VisitWrap);
    }
    return listVisitWrapper;
            }   
            
    @AuraEnabled( cacheable = true )  
    public static VisitWrapper getPatientNameFromVisit(Id visitId) {
        List<Visit__c> visit= [ SELECT Id, Patient__r.Name, Patient__r.Id
                                FROM Visit__c
                                WHERE Id = :visitId
                                ];
        Id MCId;

        for(Patient__c patient: [ SELECT Id, (SELECT Id FROM Medical_cards__r)
                                FROM Patient__c
                                WHERE Id = :visit[0].Patient__r.Id
                                ]){
            for(Medical_card__c MC : patient.Medical_cards__r){
                MCId = MC.Id;
            }
        }     

        VisitWrapper VisitWrap = new VisitWrapper();
        VisitWrap.PatientName = visit[0].Patient__r.Name;
        VisitWrap.medicalCardId = MCId;

        return VisitWrap;
        
    }
    @AuraEnabled
    public static String updateVisit(Id visitId) {                 
        List<Visit__c> visits = new List<Visit__c>();
        for (Visit__c visit : [ SELECT Id, Patient__r.Name, Doctor__c, StartDate__c 
                            FROM Visit__c
                            WHERE Id = :visitId
                            ]) {
        visit.endDate__c = System.now().addHours(-16);
        visits.add(visit);              
                            }
        update visits;
        return 'success';
                        }

    
    @AuraEnabled ( cacheable = true ) 
    public static List< VisitWrapper > getSearchVisit( String searchKey ) { 
    List<VisitWrapper> listVisitWrapper = new List<VisitWrapper>();

    String strKey = '%' + searchKey + '%';  
    for (Visit__c visit :[SELECT Id, Name, Patient__r.Name, StartDate__c, EndDate__c 
                          FROM Visit__c WHERE Patient__r.Name 
                          LIKE: strKey  ]) {


    VisitWrapper VisitWrap = new VisitWrapper();
    VisitWrap.Id = visit.Id;
    VisitWrap.PatientName = visit.Patient__r.Name;
    VisitWrap.StartDate = visit.StartDate__c.format( 'dd/MM HH:mm' );
    VisitWrap.EndDate = visit.EndDate__c.format( 'dd/MM HH:mm' );
    listVisitWrapper.add(VisitWrap);
    }
    return listVisitWrapper;    
    }                    
            

          


    public class VisitWrapper {

        @AuraEnabled
        public String Id;
        @AuraEnabled
        public String PatientName;
        @AuraEnabled
        public Boolean isActive;
        @AuraEnabled
        public String StartDate; 
        @AuraEnabled
        public String EndDate; 
        @AuraEnabled
        public String medicalCardId; 
    }
 
}